# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerivativeImage',
            fields=[
                ('created_date', models.DateTimeField(auto_created=True)),
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('checksum', models.CharField(max_length=25)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'JPEG'), (1, 'PNG')])),
                ('image_class_size', models.IntegerField(choices=[(0, 'small'), (1, 'medium'), (2, 'large')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterImage',
            fields=[
                ('created_date', models.DateTimeField(auto_created=True)),
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('checksum', models.CharField(max_length=25)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'JPEG'), (1, 'PNG')])),
                ('external_identifier', models.CharField(max_length=100)),
                ('image_class', models.IntegerField(choices=[(0, 'media_banner'), (1, 'media_tile'), (2, 'nav_banner')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='derivativeimage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetserver.MasterImage'),
        ),
    ]
