# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetserver', '0003_auto_20180208_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivativeimage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='masterimage',
            name='type',
        ),
        migrations.AddField(
            model_name='derivativeimage',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'JPEG'), (1, 'PNG')], null=True),
        ),
        migrations.AddField(
            model_name='masterimage',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'JPEG'), (1, 'PNG')], null=True),
        ),
        migrations.AlterField(
            model_name='derivativeimage',
            name='image_class_size',
            field=models.IntegerField(choices=[(0, 'thumbnail'), (1, 'tile_web'), (2, 'tile_mobile_1x'), (3, 'tile_mobile_2x'), (4, 'tile_mobile_3x')]),
        ),
        migrations.AlterField(
            model_name='masterimage',
            name='image_class',
            field=models.IntegerField(choices=[(0, 'normal_tile'), (1, 'featured_tile')]),
        ),
    ]
