# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 12:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assetserver', '0004_auto_20180314_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_service', models.IntegerField(choices=[(0, 'AZURE')])),
                ('identifier', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='derivativeimage',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'JPEG'), (1, 'PNG')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterimage',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'JPEG'), (1, 'PNG')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='azurebackup',
            name='linked_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetserver.MasterImage'),
        ),
    ]
