# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetserver', '0005_auto_20180319_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azurebackup',
            old_name='contact_info',
            new_name='derivatives',
        ),
    ]
