# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assetserver', '0006_auto_20180319_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azurebackup',
            name='id',
        ),
        migrations.AlterField(
            model_name='azurebackup',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
